apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
spec:
  rules:
  - host: registry-st.tramitaya.com.ar
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
  - host: jenkins-st.tramitaya.com.ar
    http:
      paths:
      - backend:
          serviceName: echo2
          servicePort: 80
